#ifndef _HEADER_DRIVERDESCRIPTION_H
#define _HEADER_DRIVERDESCRIPTION_H

#define DRIVER_AUTHOR "NAIRITYA KHILARI <nkmann2@gmail.com>"
#define DRIVER_DESC "A Basic Firewall."

MODULE_LICENSE("GPL");
MODULE_AUTHOR(DRIVER_AUTHOR);
MODULE_DESCRIPTION(DRIVER_DESC);

MODULE_SUPPORTED_DEVICE("UBUNTU 14.04");

#endif /* _HEADER_DRIVERDESCRIPTION_H */